// Events of proyect
export const GLOBAL_ACTIONS = {
  CHANGE_THEME: 'CHANGE_THEME',
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
  CHANGE_TRENDING: 'CHANGE_TRENDING',
  CHANGE_PAGE: 'CHANGE_PAGE',
  CHANGE_TITLEPAGE: 'CHANGE_TITLEPAGE',
};

export const TRENDING_ACTIONS = {
  ADD_TRENDINGS: 'ADD_TRENDINGS',
  ADD_BLOCK: 'ADD_BLOCK',
  CLEAN_LIST: 'CLEAN_LIST',
  ADD_INFO: 'ADD_INFO',
};

export const EVENTS_ACTIONS = {
  ADD_EVENTS: 'ADD_EVENTS',
  ADD_IMAGEOFDAY: 'ADD_IMAGEOFDAY',
};
