//Events of proyect
export const GLOBAL_ACTIONS = {
  CHANGE_THEME: "CHANGE_THEME",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
};

export const TRENDING_ACTIONS = {
  ADD_TRENDINGS: "ADD_TRENDINGS",
  ADD_BLOCK: "ADD_BLOCK",
  CLEAN_LIST: "CLEAN_LIST",
  ADD_INFO: "ADD_INFO",
};
